{% set version = "0.3.2" %}

package:
  name: clickhouse-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-{{ version }}.tar.gz
  sha256: 267f3a9a1d0d186eb99a41895a684922d31125cea21702cd7dc73af1ccdd10e7

build:
  number: 0
  # clickhouse-driver isn't available on s390x and aarch64.
  skip: True  # [py<37 or (linux and (s390x or aarch64))]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python
    - clickhouse-driver >=0.1.2
    - requests
    - sqlalchemy >=2.0.0,<2.1.0
    - asynch >=0.2.2

test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  dev_url: https://github.com/xzkostyan/clickhouse-sqlalchemy
  doc_url: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple ClickHouse SQLAlchemy Dialect
  description: |
    Simple ClickHouse SQLAlchemy Dialect.

extra:
  recipe-maintainers:
    - kszucs
    - xzkostyan
