travis:
  secure:
    BINSTAR_TOKEN: K5IVOdxFEdzd9RLs0YGkq1DkxN6ag2uh285tGheEuP3V4K4S2+OsimSf3l4b5313xb0KlnvKbpHgeCja6nfod3mIyOBwc5PeX/TfBZeaMYhnl94YxIfyNb6kRW7rAvTwSXzPfjDlJjrku6Qgl8zoWfNvFbsmCXJ/B1G1oOMbcfXzsShl9wM2wdMdUYjqRCd07+lK88qGWqYGxjlIXX9OjQ+jREDxyV5abh+Gb8LOYmqHyJ4xikq05VtTmqvfrTcVEAR576DW+djXjN4iZaucl9hq7F5RZNPIS2g7n9KQWi0vVOvYnG8pR29sNn4MpU2SRTJ9RG/YitD2TIoiob5809iQw7D9D3llJPOpv7BxlwZPAZcF8gEo7IB3W2D9PTECl99+zTMu4WTE0KMjC9YoCEN4jV08DdHRSnQuwAgWaqfymtV6eQzL2QljOCOgdTisDP56pIfk21yR/tcv+/umMdd0qeauQPbqU5BY/qkWF6m4rdwXFhMtioi3vBimVKgdXt5h9AB1sd46T90pTNu769t8lXZ2uF1fLIySk5yri5o+xoqloVpFBp/aMFnwCF2nK1QJoK8RVJc8Bw6cSgkvMAWH1Xbxour146SzS0ZZNwGeBK3NKyDR3bvziz3aaSw8ApM2M6e0DSQy0nOVaTaz/VFFx5BbqyafkH3Sj+7E02M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
