travis:
  secure:
    BINSTAR_TOKEN: ATjrH0htp/Sd+g9EMcJkH6AoGDoHl5U6GEdXY0xihJr/gXOUUaedJ2SIkDA8jdJAt54BHbngyEPvLztDeom+jeCaMpi89gGYwGutDh2DhQAK2YV28o56rm5fa1xLNiftFPM+XaAFScSrSIp4joH1sG5wYeP/2ht90GD/W5Y8slkjbHlpCYAGfWz2AOq5AKMT01HvwMLi0gno9/V2RK0gzZHKrAbCb/nDUYLzo/qFkBNJN0FUpWpGsYthA0vAUDG7MceBpkLrt2v26e3nBZ/r+n52qZB9qFE9XiW7qy5EHtRCmFnHI/LSd/BbqVNA+qHAxy2yqlzjkafbKeWwMj+aWZ8UPQeJEkMOB53ZlEn7F3FMEpj9Gu+rkCh9jOhBCh4kEuQGr+tuTkLtMrhtG8hS6Kze0iPK/8QEnkUuQnWE20oLXFubW43G8/g2ljeRyKJxNDarjJbtRjsXpYDSOZxRZ2QcTC3VnjPXWA3GOoYi79WPhBVSfaXDeb0HyLKUVO7tMuHKzkLoD2Pdb+SwucWRweoQB7EDEWGkeBBO6YNJWE0i0DTb7UfE2MBuMBvdfwCCu+yTs7tWxGzbqqxAP2uDOt8u0eYYwfbOJBVOTf+TM9fkgFlHnRGUW9ipF4eQ5SdminpE2VUyT2lQEnVKgjLSswAlX18h9qgrgbxvqwP89HA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
