travis:
  secure:
    BINSTAR_TOKEN: IEgsKRckOKZI6RhGK5aIPw7gO0wk6h8YZhiGcos90hsdldxtH0NWd5cagvHuoXOh6o2dhxwuqorzCflk839MCImNk7f3GmnwKbgA+zv1myBoaTbbvYuKedjX1UwE415QqxQRbpnXOecP6/YEzi1b0QhjLwDwXjqaLk7CW0xXtlZn0SWV0LH3DF37KYPb7DMBrZMFrevm6DW8G5kdAl+N9bghkJ2/cUrPnnqnL6OV6CpVPhqJWALfgQ7g0wnAvQqmGB3UWpQRlXAsXDZ1ZdISJRrrZOXiVpqcstxpjvFReA7sXAQf8o0GU9tFqmLdbc4x/9XfYJeMowEUNPfzXdYwVyzNnNIrpVSDAjguY7iHqSd48OQexqyix4a4oz8wFoaFVxqc0TH3liPKjhkPC3NEZDUryAIohrE1vRBY8tIu1ZxrwlD1O6YO7Hfxt6RtFi1NhnkdjwWdMG9DbRkQFJgbi60nGgcsaSfEoNQutNWGaqFLivtGrnR1etBl2pm0X6FZRSD2wLuls7C8cvzejsFOkAuV8rkIu2UD3/MkWH6b8+3mmnTrMnwIbj5FrWJZMJZ/NTICJnP3Z4Qhm/NfkgMMmPVzyABz8lBM8STg9jP1dWPLp+udW6o5ZfFoJzlxWFZQ9u6oSLHCjDorc4qha/kRIOltOgoBrJSst5JlkGZzNmM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
